### ISSUE TITLE
handle keystore for windows

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-contract-api#3]
RIght now, keystore works only for OSX
Needs to detect if the lib runs on windows and make it work for it

**Comment by kivanov82** [comment]
+1 
Or at least configurable in FacadeProvider constructor

**Comment by adridadou** [comment]
I should have a look at web3j utils to load keystore. he is handling linux / windows already

**Comment by adridadou** [comment]
I'm using web3j now
