### ISSUE TITLE
No sendTx() for void methods

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-contract-api#32]
In case a contract method return type is 'void' the transaction doesn't get sent.

**Comment by kivanov82** [comment]
To reproduce: see TestnetConnectionTest.run() the line with myContract.myMethod2 call.
Happens once switched to the testNet

**Comment by adridadou** [comment]
I'll have a look this weekend.

**Comment by adridadou** [comment]
So I have found the issue but I realized that the latest ethereumJ version makes some problem.
I'll close this when I resolve the issue and merge everything

**Comment by adridadou** [comment]
done!
