### ISSUE TITLE
simple test framework for smart contract

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-contract-api#33]
Here is the idea:
With StandaloneEthereum + the interface, it should be fast and easy to test a smart contract.

We should have a way to write simple unit tests for it to make sure it works well.

**Comment by UrsZeidler** [comment]
I have started a documentation (https://github.com/UrsZeidler/uml2solidity/wiki/TestWithJava) to setup a project for junit tests with your lib together with the code generator I'm working on. 

Currently I'm trying several projects of mine to test this out. 

One issue I encounter, I'm not sure if you are the right address for it, when I have a set of contracts in several files  it won't compile as we sent the contract code via stdIn to the compiler, so the compiler has no chance to get the included contract files. At least I have found no way. I think this is an issue of ethereumj.

I build the code generator against the 0.9-snapshot version and I have noticed some changes in the head which would need some adjustments, do you have a time line for your next release ?

Together with the solidity editor for eclipse (https://github.com/webdaford/smart-contract-tools) this gives us the opportunity to develop pure in eclipse. (I'm a big fan of eclipse) Another step could be to bundle your library as eclipse plugin and add some wizards for the project setup to avoid the manual project setup.

**Comment by adridadou** [comment]
Hi!
First I think this is awesome what you're doing !! 
For your issue regarding imports, you are right I am simply using the solc integration from ethereumJ. But this is a very good question and I'd love to see a solution to that. I propose you create an issue for that and I'll have a look

For the next release, I am working hard to have a first version of the RPC backend. As soon as this is ready I will make a new release. 

Regarding testing, another thing I'd love to do is using the CPU mining of ethereumJ to avoid using this mocked blockchain and do something a bit more realistic. Also I would like to be able to define accounts with specific balance. 

Anyway keep up the good work, and let's keep in touch

**Comment by adridadou** [comment]
Regarding the import "..." part, I think we're going to need to implement it ourselves. I'll create an issue about it

**Comment by adridadou** [comment]
The other thing, The blockchainTest is nice but I think I've mocked a bit too much there. 
I will leave it becauae it is still a good way to make some tests very fast but I'll be working now on an easy way to do integration tests with a simple private network.

The features will be:
1. One node local private network
2. Genesis.json defined in code. This way you can define the balances of different accounts in your test
3. ConfigBuilder to define all that. 
4. Hopefully not too slow

P.S: I've done a new release

**Comment by UrsZeidler** [comment]
Such a controllable private test chain would be great.
It would open a wide range of use cases.

In my opinion unit tests need to be fast. Adding a switch to change the blockchain implementation should be not to hard. 

I will look into the release and adopt the changes, my plan is to release in the next few days, cool timing.
Thanks for your good work.

**Comment by adridadou** [comment]
Cool!
Yeah at the end we are talking about using a different provider ,that's it. 

Looking forward to your release as well!

**Comment by adridadou** [comment]
Ok I have created the integration tests possible by having a local private network

The only drawback is that you need to generate the DAG but I made it sure that you need to generate it only once

**Comment by UrsZeidler** [comment]
NIce to see, currently I'm a bit occupied, will look to it later in the week.
