### ISSUE TITLE
Implement import "..." capability for solidity

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-contract-api#36]
You can find the documentation of how import works here : http://solidity.readthedocs.io/en/develop/layout-of-source-files.html

The idea would be to simulate the import by replacing it with the actual code.  Because the import logic is fairly complex, this story will be split into multiple sub issues for each import feature. The first one being to simply import a file as is.

**Comment by UrsZeidler** [comment]
This was what I was thinking ;). (epic)

But maybe we could let the compiler do the work, if we don't send it the code but instead collect all the files and send these files to the compiler.  

In the unl2solidityproject I have a simple solc starter class which uses this approach, it collects all the generated solidity files and compiles it by calling the compiler with all the collected files. 

Using the simple call:

> solc [options] [input_file...]

From my experience these files need to be absolute, but I not perfectly sure about it.

We would also need to 'parse' the file but extract only the affected files. Which sounds much simpler.
The only catch is ethereumj does not support this (from what I saw in `org.ethereum.solidity.compiler.SolidityCompiler`). We would need to file them a feature request to make this possible.

**Comment by adridadou** [comment]
Doing it that way (the way i describe in the epic) is that I can make it work not only with the file system but any other mean. Imagine being able to put an URL there or anything like that.

It is maybe possible to do what you say but I doubt it ... 

The idea here will be to have a preprocessor that will prepare the string before sending it to the SolidityCompiler. I don't find it too bad that you can have simple strings, you don't necessarily need files to make it work

**Comment by adridadou** [comment]
https://github.com/ethereum/ethereumj/tree/develop/ethereumj-core/src/main/java/org/ethereum/solidity/compiler This from EthereumJ could be a nice way to at least start this work

**Comment by adridadou** [comment]
Let's focus on import "myfile.sol" and nothing else
