### ISSUE TITLE
Should wait for the result from void-typed contract functions

### ISSUE THREAD

**Issue by dstarcev** [adridadou/eth-contract-api#48]
According to [the description in the wiki](https://github.com/adridadou/eth-contract-api/wiki/How-to-create-a-proxy-to-a-smart-contract#ethereumfacadeprovider) void-typed methods are considered as requiring a transaction. 
I believe it's not a good idea to ignore the result of a transaction since semantically `void` means `work has been done`. If a user needs such a behavior, they can make the method return `CompletableFuture<Void>` and not to wait for the completion intentionally.

Here is a tiny PR addressing the issue #47

**Comment by adridadou** [comment]
You're right.
This is what happens when the library evolves :)
