### ISSUE TITLE
Add getNonce() to the EthereumFacade

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-contract-api#52]
It would be great to make method 
BigInteger getNonce(final EthAccount account)
available in EthereumFacade.

**Comment by adridadou** [comment]
This is not a problem.
The only question is, which value should I return?
There are two options:
1. The actual current Nonce, i.e. the one you would get from the RPC call
2. The calculated Nonce, i.e. the actual Nonce + the number of pending transactions

**Comment by kivanov82** [comment]
I'm personally interested in 2) but for the future needs perhaps both make sense.

**Comment by adridadou** [comment]
done
