### ISSUE TITLE
handle events

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-contract-api#6]
It should be possible to listen to events and react to them

**Comment by zhouyuanbin** [comment]
How to set listener with event in java ? Thank you!  @adridadou

**Comment by adridadou** [comment]
Hi, as you can see this issue is still open. Right now it is not possible. 
I need to check first how events are handled in EthereumJ, I am not sure if they are or not. Then I can implement and developer friendly way to do it.

**Comment by zhouyuanbin** [comment]
Thanks

**Comment by zhouyuanbin** [comment]
Another question how to call the contract method below?
< 
     function getValue(address addr, bytes32 key) constant returns(bytes){
            return data[addr][key].value;
      }
>

**Comment by zhouyuanbin** [comment]
Another question how to call the contract method below?
< 
     function getValue(address addr, bytes32 key) constant returns(bytes){
            return data[addr][key].value;
      }
>

**Comment by zhouyuanbin** [comment]
Another question how to call the contract method below?
< 
     function getValue(address addr, bytes32 key) constant returns(bytes){
            return data[addr][key].value;
      }
>

**Comment by adridadou** [comment]
What you need to do is you have to create a proxy to your smart contract.
https://github.com/adridadou/eth-contract-api/wiki/How-to-create-a-proxy-to-a-smart-contract

This is basically an interface representing your smart contract where you define a method representing your function.

Regarding mapping, I am using the mapping EthereumJ is using. I am not entirely sure but I would guess bytes32 should map to String or at least byte[]. The same for bytes.

In the wiki page there is a link to an example. Let me know if this is unclear

**Comment by zhouyuanbin** [comment]
OK. Thanks

**Comment by adridadou** [comment]
thx to @Kiril Ivanov for this PR
