### ISSUE TITLE
Add a way to deploy the contracts with a created CompilationResult.

### ISSUE THREAD

**Issue by UrsZeidler** [adridadou/eth-contract-api#64]
Why not provide a way to deploy the contracts via _org.ethereum.solidity.compiler.CompilationResult_ because a created and configured CompilationResult could be make from every parser by hand (hardcoded) also by tool.

This would helps a bit for #36 and followings because the solc compiler did the resolving, and also for #50 as it give a way to use the own compiler not a provided one.(Maybe you want to build the compiler your self.)

**Comment by adridadou** [comment]
Interesting idea. 
If we want to go this road, I think we need to think a bit more what represents a CompilationResult. 

I want to keep the API as neutral as possible so using the EthereumJ class is suboptimal I think.

I would take the idea a bit further and try to create an abstract interface to deploy a smart contract.
This could be the source code, compiled raw data, any other thing ...

**Comment by adridadou** [comment]
Actually I had to do that for me to remove duplicated code for compilation
