### ISSUE TITLE
EthereumEventHandler handles DROPPED transaction incorrectly

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-contract-api#72]
EthereumEventHandler.onTransactionExecuted() treats 'DROPPED' transaction as 'INCLUDED'.

It turned out that dropped transaction might be handled both by onPendingTransactionUpdate() (works fine) OR onTransactionExecuted() (bug)

Dropped transaction can be distinguished by summary.isFailed() so that this line would look like:

> onTransactionHandler.onTransaction(new OnTransactionParameters(summary.getTransaction(), summary.isFailed()? PendingTransactionState.DROPPED : PendingTransactionState.INCLUDED));

Sorry, it was my piece of code ;)

**Comment by adridadou** [comment]
good catch. I haven't seen that. I'll fix that soon (or you can do a PR if you want)

**Comment by kivanov82** [comment]
Upd: there is something I cannot explain but:
if tx is dropped it still can happen that onPendingTransactionUpdate() is called with the state='INCLUDED'.

So that method must be fixed manually too checking first txReceipt.isSuccessful(). If not - than this transaction was actually dropped rather than included.

**Comment by adridadou** [comment]
you mean that a state is INCLUDED but it is not successful? 
that doesn't make a lot of sense ....

**Comment by adridadou** [comment]
question, do you really need onPendingTransactionUpdate ? Isn't it enough to have onTransactionExecuted ?

**Comment by kivanov82** [comment]
Yes, I want to keep the list of 'pending' transactions locally too.

**Comment by adridadou** [comment]
I just thought about it and a transaction can fail yet be included.

isSuccessful means that the EVM didn't throw any exceptions. But if you have an OutOfGas, invalid JUMP dest or any other error, the transaction is still included but has no effect

**Comment by kivanov82** [comment]
I see. 
To my mind 'dropped' rather means the state of the chain was not changed, but perhaps it's just me. :)

So to my mind we have 2 options - either change the logic in EthereumEventHandler or just pass txReceipt/summary further to onTransactionHandler allowing people to decide how to handle it.

**Comment by adridadou** [comment]
The transaction has been included, i.e. it is part of a block. 

I think this part has to be reworked a bit.
First, I'd love to remov the dependency to EthereumJ (with the state being passed in the object) and again it all depends what you are looking for.
I think that having information about the state, was it successful or not, makes sense

**Comment by adridadou** [comment]
I close this issue as #73 is the follow up issue
