### ISSUE TITLE
All transactions are DROPPED at one stage

### ISSUE THREAD

**Issue by kivanov82** [adridadou/eth-contract-api#73]
Might be related to #72 but at one stage the queue of pendingTransactions in BlockchainProxyReal doesn't get cleaned which leads to the incorrecly calcualated nonce so that all the subsequent transactions are dropped either.

Not sure about the 'at one strage' yet, but seams shooting 10-15 transactions every second-two will lead to that.

**Comment by adridadou** [comment]
I have to write tests about that. But my suspicion is:
- you send 15 transactions (almost) at once.
- You calculate the nonce for each of them
- The third transaction is being dropped
- You have now a "hole" in your nonce, and that makes all the other transactions being dropped

**Comment by adridadou** [comment]
I suspect now that this was an issue due to the mismanagement of gasLimit. 
@kivanov82 can u pull develop and try again and let me know if you still have many dropped tx ?

**Comment by adridadou** [comment]
After a few discussions with @kivanov82  it seems that this is not a problem  anymore.
I propose to close this one and open it again if the problem resurface
