### ISSUE TITLE
Create a small library for better exception handling

### ISSUE THREAD

**Issue by adridadou** [adridadou/eth-contract-api#74]
The idea is the following: 
Create a simple smart contract / library you can include in your solidity code with the function throwException(string message) 

The function will do the following:
- Write an event of type Exception with the given message
- call 'throw'

On the java side, whenever a throw is detected, we will look if an event exists and if yes, we'll recreate a more verbose error message

**Comment by kivanov82** [comment]
Nice idea, really missing it a lot at the moment.
But there is no easy way to listen/search for the event at the moment, isn't it?

**Comment by adridadou** [comment]
You're right. This task has a dependency to the one talking about listening to events from EthereumJ / RPC

**Comment by adridadou** [comment]
After a discussion on gitter, it seems that it isn't that easy. Events are also rolled back ... I'll need to find another way

**Comment by adridadou** [comment]
I'll close that for now. Having better error handling is needed for sure but I have no clear plan right now and the approach discussed here is not applicable
