### ISSUE TITLE
Support multiple return types?

### ISSUE THREAD

**Issue by jacohend** [adridadou/eth-contract-api#96]
How does one support multiple Solidity function return types in Java? Does the data come back as an array of returned objects?

**Comment by adridadou** [comment]
Hi, sorry I haven't had a chance to write a proper documentation yet.

The idea is to create a class that represents the value.
So let's imagine you have this function: 
function getM() constant returns (bool,string,uint) {
    return (true,"hello",34);
}


What you need is to define a class with three properties and a constructor like this:
public static class MyReturnType {
        private final Boolean val1;
        private final String val2;
        private final Integer val3;

        public MyReturnType(Boolean val1, String val2, Integer val3) {
            this.val1 = val1;
            this.val2 = val2;
            this.val3 = val3;
        }

// getters and setters
}

You can find this example in TestnetConnectionTest

**Comment by jacohend** [comment]
Ah thanks man, was pulling my hair out trying to write a interface for a multiple return function
